use std::cmp::Ordering;
use std::collections::{HashMap, VecDeque};
use crate::tree::HuffmanTree;

/// Specific implementations for the huffman tree type that's used in encoding and decoding.
impl HuffmanTree<u64> {
    /// Build a new tree from a serialised tree. Upon success, returns both the created tree and the
    /// data offset.
    /// Can take the full encoded file data with the tree at the start. Excess data will be ignored,
    /// and the start byte index of the excess data is returned upon success.
    ///
    /// The `offset` parameter is meant for specifying the length of the file header. The first
    /// `offset` number of bytes in `data` will be skipped.
    ///
    /// Due to the compact way the tree is stored, there aren't many ways to verify that the given
    /// data is actually a tree.
    pub fn deserialise(data: &Vec<u8>, offset: usize) -> Result<(Self, u32), String> {
        if data.len() < 3 + offset {
            return Err(String::from("Insufficient data to parse tree header"));
        }

        // Get tree header data
        let tree_depth = *data.get(offset + 0).unwrap() as u32;
        let count_size = *data.get(offset + 1).unwrap() as u32;
        let chunk_size = *data.get(offset + 2).unwrap() as u32;

        // Phase 1 helper variables
        let mut count_stack: VecDeque<u32> = VecDeque::new();
        let mut counts_left = tree_depth;
        let mut current_level = 1;

        // Resulting tree
        let mut tree = HuffmanTree::new();

        // Input buffer to convert from 8-bit to variable data chunks
        let mut buffer = 0u128;
        let mut buffer_size = 0u32;

        // For returning the data offset at the end
        let mut index = 0;
        for byte in data {
            // Skip the offset and the 3 bytes we considered before
            if index < offset + 3 {
                index += 1;
                continue;
            }

            // Load next byte into the buffer
            buffer <<= 8;
            buffer_size += 8;
            buffer |= *byte as u128;

            if counts_left > 0 {
                // Phase 1, gathering counts

                // While we have enough data to parse one or more counts
                while buffer_size >= count_size && counts_left > 0 {
                    buffer_size -= count_size;
                    let next_count = (buffer >> buffer_size) as u32;
                    buffer &= !(u128::MAX << buffer_size);
                    counts_left -= 1;

                    for _x in 0..next_count {
                        count_stack.push_front(current_level);
                    }
                    current_level += 1;
                }
            } else if !count_stack.is_empty() {
                // Phase 2, gathering values and paths
                while !count_stack.is_empty() &&
                    buffer_size >= chunk_size + count_stack.front().unwrap() {
                    // Number of bits for the next path
                    let next_level = count_stack.pop_front().unwrap();
                    // Take the value out of the buffer
                    buffer_size -= chunk_size;
                    let next_value = (buffer >> buffer_size) as u64;
                    buffer &= !(u128::MAX << buffer_size);

                    // Take the path out of the buffer
                    buffer_size -= next_level;
                    let next_path = (buffer >> buffer_size) as u32;
                    buffer &= !(u128::MAX << buffer_size);

                    // Put value and path into the tree
                    tree.set(next_value, next_path, next_level);
                }
            } else {
                // If neither of the if conditions are true, then we have parsed the tree
                break;
            }

            index += 1;
        }

        return Ok((tree, index as u32));
    }

    /// Generate a compact binary representation of this tree. A new tree can be generated by calling
    /// [HuffmanTree<u64>::deserialise] and providing the output of this function.
    pub fn serialise(&self, bits: u32) -> Result<Vec<u8>, String> {
        /*
            Serialisation layout:
            First 3 bytes, data:
                - Tree depth (1 byte): Number of levels in the tree
                - Count size (1 byte): Number of bits that the count per level takes up
                - Chunk size (1 byte): Size in bits of data chunks that were taken from the input

            Second, for each level in the tree, from 1 to and including the 'tree depth' level,
            note the count in 'count size' number of bits. At the end, the byte is not padded with
            zeros if it isn't full.

            Third, for each value in the tree, sorted by level from highest level value to lowest,
            note the value in 'chunk size' number of bits, and note the path in the number of bits
            of that level. A deserialiser keeps track of the number of values of each value it has
            parsed to know how many bits each path takes up.

            After the last step, the current byte is filled up with zeros until it is full. If the
            data perfectly aligns with a byte, no padding is added.
        */

        if bits > 64 {
            return Err(String::from("Chunk size value (bits) cannot be greater than 64"));
        }

        // Get all values in the tree, with paths and levels
        let mut all_values = self.get_all_values_with_paths(0, 0);
        // Sort them by level, lowest level (highest number) to highest
        all_values.sort_by(|(_val_a, (_path_a, lvl_a)), (_val_b, (_path_b, lvl_b))| {
            if lvl_a > lvl_b {
                Ordering::Less
            } else if lvl_a == lvl_b {
                Ordering::Equal
            } else {
                Ordering::Greater
            }
        });

        if all_values.is_empty() {
            return Err(String::from("Cannot serialise empty tree"));
        }

        let chunk_bit_size = bits as u8;

        // Highest level in the tree, lowest level number
        let min_level = {
            let (_, (_, x)) = all_values.get(0).unwrap();
            *x as u8
        };

        let mut count_map: HashMap<u32, u32> = HashMap::new();
        for (_value, (_path, level)) in &all_values {
            if let Some(count) = count_map.get_mut(level) {
                *count += 1;
            } else {
                count_map.insert(*level, 1);
            }
        }
        let max_count = count_map.iter().map(|(_, count)| *count).max().unwrap();
        let min_bits_for_count = (max_count.ilog2() + 1) as u8;

        let mut output = Vec::new();

        // Add header information
        output.push(min_level);
        output.push(min_bits_for_count);
        output.push(chunk_bit_size);

        if chunk_bit_size + min_level > 128 {
            return Err(format!("Cannot fit chunk size {} and path length {} in the buffer", chunk_bit_size, min_level))
        }

        let mut buffer = 0u128; // We need space for both the value and its path
        let mut buffer_size = 0;

        add_level_counts(&mut output, &mut buffer, &mut buffer_size,
                         &count_map, min_bits_for_count, min_level);

        add_values_and_paths(&mut output, &mut buffer, &mut buffer_size, &all_values, bits);

        // It can never be greater than 7
        if buffer_size > 0 {
            let last_byte = (buffer << (8 - buffer_size)) as u8;
            output.push(last_byte);
        }

        Ok(output)
    }
}

// Adds the level counts to the output/buffer, from level 1 to `level_count`
fn add_level_counts(output: &mut Vec<u8>,
                    buffer: &mut u128,
                    buffer_size: &mut u32,
                    count_map: &HashMap<u32, u32>,
                    count_size: u8,
                    min_level: u8,
) {
    // Get all counts in order, and 0 for levels that have no values
    let mut counts = Vec::new();
    for level in 1..=min_level {
        if let Some(count) = count_map.get(&(level as u32)) {
            counts.push(*count)
        } else {
            counts.push(0);
        }
    }

    // Add everything to the buffer and then output vector
    for count in counts {
        *buffer <<= count_size as u128;
        *buffer_size += count_size as u32;
        *buffer |= count as u128;

        buffer_to_output(buffer, buffer_size, output);
    }
}

// Add values and paths to the tree/buffer starting at values with the highest level number
// and going to values with level 1 (if they exist)
fn add_values_and_paths(output: &mut Vec<u8>,
                        buffer: &mut u128,
                        buffer_size: &mut u32,
                        all_values: &Vec<(&u64, (u32, u32))>,
                        bits: u32) {
    for (value, (path, level)) in all_values {
        // Add the value
        *buffer <<= bits as u128;
        *buffer_size += bits;
        *buffer |= **value as u128;

        // Add the path
        *buffer <<= *level as u128;
        *buffer_size += *level as u32;
        *buffer |= *path as u128;

        buffer_to_output(buffer, buffer_size, output);
    }
}

fn buffer_to_output(buffer: &mut u128, buffer_size: &mut u32, output: &mut Vec<u8>) {
    while *buffer_size >= 8 {
        *buffer_size -= 8;
        let next_byte = (*buffer >> *buffer_size) as u8;
        *buffer &= !(u128::MAX << *buffer_size);
        output.push(next_byte);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn serialise() {
        let mut tree = HuffmanTree::new();
        tree.set(1u64, 0b00000, 5);
        tree.set(2u64, 0b0001, 4);
        tree.set(3u64, 0b0100, 4);
        tree.set(4u64, 0b01010, 5);
        tree.set(5u64, 0b01011, 5);
        tree.set(6u64, 0b011, 3);
        tree.set(7u64, 0b101111, 6);
        tree.set(8u64, 0b11, 2);

        let encoding_map = tree.generate_encoding_map();

        let serialisation = tree.serialise(8);
        assert!(serialisation.is_ok());

        let maybe_tree = HuffmanTree::deserialise(&serialisation.unwrap(), 0);
        assert!(maybe_tree.is_ok());
        let new_tree = maybe_tree.unwrap();
        let encoding_new = new_tree.0.generate_encoding_map();

        assert_eq!(encoding_new, encoding_map);
    }
}